#syntax=docker/dockerfile:1
FROM golang:1.25-alpine AS build-stage
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /app/order-service ./cmd/order-service
#Tests
FROM build-stage AS run-test-stage
RUN go test -v ./...
#Release build
FROM alpine:3.19
WORKDIR /
COPY --from=build-stage /app/order-service /app/order-service
COPY --from=build-stage /app/web /app/web
EXPOSE 8080
CMD ["/app/order-service"]